apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
      - name: go-webserver
        image: willicentmbugua/webserver:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-webserver-service
spec:
  selector:
    app: go-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # You can change this port if needed (range: 30000-32767)
  type: NodePort